url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Heximath" # the name of your site, e.g. ACME Corp.

# Build settings
markdown: kramdown

collections:
  blog_posts:
    output: true
    permalink: /posts/:title