url: "https://uwukia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/heximath" # the subpath of your site, e.g. /blog
title: "Heximath" # the name of your site, e.g. ACME Corp.
ref: "https://uwukia.github.io/heximath/posts"

# Build settings
markdown: kramdown

collections:
  blog_posts:
    output: true
    permalink: /posts/:title